import torch
from torch import nn
from torch import Tensor
import torch.nn.functional as F
import torch.utils.checkpoint
import contextlib
import torchvision
import numpy as np

import math
from stgcn_layers import Graph, get_stgcn_chain
from deformable_attention_2d import DeformableAttention2D
import warnings

from einops import rearrange, repeat
from transformers import MT5ForConditionalGeneration, T5Tokenizer 
from transformers.modeling_outputs import (
    BaseModelOutput
)

from models.tools import X_CrossAttn, _expand_mask, EmbeddingClusterHelperAutomaton, gloabal_similarity_loss, tokenwise_similarity_loss
from config import mt5_path, mt5_aux_path
from utils import KLLoss

def _no_grad_trunc_normal_(tensor, mean, std, a, b):
    # Cut & paste from PyTorch official master until it's in a few official releases - RW
    # Method based on https://people.sc.fsu.edu/~jburkardt/presentations/truncated_normal.pdf
    def norm_cdf(x):
        # Computes standard normal cumulative distribution function
        return (1. + math.erf(x / math.sqrt(2.))) / 2.

    if (mean < a - 2 * std) or (mean > b + 2 * std):
        warnings.warn("mean is more than 2 std from [a, b] in nn.init.trunc_normal_. "
                      "The distribution of values may be incorrect.",
                      stacklevel=2)

    with torch.no_grad():
        # Values are generated by using a truncated uniform distribution and
        # then using the inverse CDF for the normal distribution.
        # Get upper and lower cdf values
        l = norm_cdf((a - mean) / std)
        u = norm_cdf((b - mean) / std)

        # Uniformly fill tensor with values from [l, u], then translate to
        # [2l-1, 2u-1].
        tensor.uniform_(2 * l - 1, 2 * u - 1)

        # Use inverse cdf transform for normal distribution to get truncated
        # standard normal
        tensor.erfinv_()

        # Transform to proper mean, std
        tensor.mul_(std * math.sqrt(2.))
        tensor.add_(mean)

        # Clamp to ensure it's in the proper range
        tensor.clamp_(min=a, max=b)
        return tensor


def trunc_normal_(tensor, mean=0., std=1., a=-2., b=2.):
    # type: (Tensor, float, float, float, float) -> Tensor
    r"""Fills the input Tensor with values drawn from a truncated
    normal distribution. The values are effectively drawn from the
    normal distribution :math:`\mathcal{N}(\text{mean}, \text{std}^2)`
    with values outside :math:`[a, b]` redrawn until they are within
    the bounds. The method used for generating the random values works
    best when :math:`a \leq \text{mean} \leq b`.
    Args:
        tensor: an n-dimensional `torch.Tensor`
        mean: the mean of the normal distribution
        std: the standard deviation of the normal distribution
        a: the minimum cutoff value
        b: the maximum cutoff value
    Examples:
        >>> w = torch.empty(3, 5)
        >>> nn.init.trunc_normal_(w)
    """
    return _no_grad_trunc_normal_(tensor, mean, std, a, b)


class Sigma(nn.Module):
    def __init__(self, args):
        super(Sigma, self).__init__()
        print("Sigma...")
        self.args = args
        
        self.modes = ['body', 'left', 'right', 'face_all']
        
        self.graph, A = {}, []
        # project (x,y,score) to hidden dim
        hidden_dim = args.hidden_dim
        self.proj_linear = nn.ModuleDict()
        for mode in self.modes:
            self.graph[mode] = Graph(layout=f'{mode}', strategy='distance', max_hop=1)
            A.append(torch.tensor(self.graph[mode].A, dtype=torch.float32, requires_grad=False))
            self.proj_linear[mode] = nn.Linear(3, 64)

        self.gcn_modules = nn.ModuleDict()
        self.fusion_gcn_modules = nn.ModuleDict()
        spatial_kernel_size = A[0].size(0)
        for index, mode in enumerate(self.modes):
            self.gcn_modules[mode], final_dim = get_stgcn_chain(64, 'spatial', (1, spatial_kernel_size), A[index].clone(), True)
            self.fusion_gcn_modules[mode], _ = get_stgcn_chain(final_dim, 'temporal', (5, spatial_kernel_size), A[index].clone(), True)
        
        self.gcn_modules['left'] = self.gcn_modules['right']
        self.fusion_gcn_modules['left'] = self.fusion_gcn_modules['right']
        self.proj_linear['left'] = self.proj_linear['right']

        self.part_para = nn.Parameter(torch.zeros(hidden_dim*len(self.modes)))
        self.pose_proj = nn.Linear(256*4, 768)
        
        self.apply(self._init_weights)
        
        if "CSL" in self.args.dataset:
            self.lang = 'Chinese'
        else:
            self.lang = 'English'
        
        if self.args.rgb_support:
            self.rgb_support_backbone = torch.nn.Sequential(*list(torchvision.models.efficientnet_b0(pretrained=True).children())[:-2])
            self.rgb_proj = nn.Conv2d(1280, hidden_dim, kernel_size=1)

            self.fusion_pose_rgb_linear = nn.Linear(hidden_dim, hidden_dim)
            
            # PGF
            self.fusion_pose_rgb_DA = DeformableAttention2D(
                                        dim = hidden_dim,            # feature dimensions
                                        dim_head = 32,               # dimension per head
                                        heads = 8,                   # attention heads
                                        dropout = 0.,                # dropout
                                        downsample_factor = 1,       # downsample factor (r in paper)
                                        offset_scale = None,         # scale of offset, maximum offset
                                        offset_groups = None,        # number of offset groups, should be multiple of heads
                                        offset_kernel_size = 1,      # offset kernel size
                                    )
            
            self.fusion_gate = nn.Sequential(nn.Conv1d(hidden_dim*2, hidden_dim, 1),
                                        nn.GELU(),
                                        nn.Conv1d(hidden_dim, 1, 1),
                                        nn.Tanh(),
                                        nn.ReLU(),
                                    )
            
            for layer in self.fusion_gate:
                if isinstance(layer, nn.Conv1d):
                    nn.init.constant_(layer.weight, 0)
                    nn.init.constant_(layer.bias, 0)

        if "CSL" in args.dataset:
            self.lang = 'Chinese'
        else:
            self.lang = 'English'
        print("The targted language is", self.lang)
        self.mt5_tokenizer = T5Tokenizer.from_pretrained(mt5_path, legacy=False)

        self.hcl = SignEFCL(self.args)
        self.stm = STM(self.args)
    
        mt5 = MT5ForConditionalGeneration.from_pretrained(mt5_path)
        self.sgt_dec = mt5.get_decoder()
        self.sgt_dec_lm_head = mt5.lm_head
        self.args.entity_dict_path = self.args.zh_enitity if self.lang == 'Chinese' else self.args.en_enitity
        self.embedding_cluster_helper = EmbeddingClusterHelperAutomaton(
            self.mt5_tokenizer,  self.args.entity_dict_path, 
            masked_token=["<pad>", "</s>", "<unk>"])
        print('Create embedding cluster helper')

    def _init_weights(self, m):
        if isinstance(m, nn.Linear):
            trunc_normal_(m.weight, std=.02)
            if isinstance(m, nn.Linear) and m.bias is not None:
                nn.init.constant_(m.bias, 0)
        elif isinstance(m, nn.LayerNorm):
            nn.init.constant_(m.bias, 0)
            nn.init.constant_(m.weight, 1.0)

    def maybe_autocast(self, dtype=torch.float32):
        # if on cpu, don't use autocast
        # if on gpu, use autocast with dtype if provided, otherwise use torch.float16
        # enable_autocast = self.device != torch.device("cpu")
        enable_autocast = True

        if enable_autocast:
            return torch.cuda.amp.autocast(dtype=dtype)
        else:
            return contextlib.nullcontext()

    def gather_feat_pose_rgb(self, gcn_feat, rgb_feat, indices, rgb_len, pose_init):
        b, c, T, n = gcn_feat.shape
        assert rgb_feat.shape[0] == indices.shape[0]
        rgb_feat = self.rgb_proj(rgb_feat)
        
        assert len(rgb_len) == b
        start = 0
        for batch in range(b):
            index = indices[start:start + rgb_len[batch]].to(torch.long)
            # ignore some invalid rgb clip
            if rgb_len[batch] == 1 and -1 in index:
                start = start + rgb_len[batch]
                continue
            
            # index selection
            gcn_feat_selected = gcn_feat[batch, :, index]
            rgb_feat_selected = rgb_feat[start:start + rgb_len[batch]]
            pose_init_selected = pose_init[start:start + rgb_len[batch]]
            
            gcn_feat_selected = rearrange(gcn_feat_selected, 'c t n -> t c n')
            pose_init_selected = rearrange(pose_init_selected, 't n c -> t c n')
            
            # PGF forward
            with self.maybe_autocast():
                fused_transposed = self.fusion_pose_rgb_DA(pose_feat=gcn_feat_selected,
                                                            rgb_feat=rgb_feat_selected, 
                                                            pose_init=pose_init_selected, )
            
            fused_transposed = fused_transposed.to(gcn_feat.dtype)
            gate_feature = torch.concat([fused_transposed, gcn_feat_selected,], dim=-2)
            gate_score = self.fusion_gate(gate_feature)
            fused_transposed_post = (gate_score) * fused_transposed + (1 - gate_score) * gcn_feat_selected
            
            gcn_feat = gcn_feat.clone() 
            fused_transposed_post = rearrange(fused_transposed_post, 't c n -> c t n')
            
            # replace gcn feature
            gcn_feat[batch, :, index] = fused_transposed_post
            start = start + rgb_len[batch]
            
        assert start == rgb_feat.shape[0]
        return gcn_feat

    def forward(self, src_input, tgt_input):
        # RGB branch forward
        if self.args.rgb_support:
            rgb_support_dict = {}
            for index_key, rgb_key in zip(['left_sampled_indices', 'right_sampled_indices'], ['left_hands', 'right_hands']):
                rgb_feat = self.rgb_support_backbone(src_input[rgb_key])
                
                rgb_support_dict[index_key] = src_input[index_key]
                rgb_support_dict[rgb_key] = rgb_feat
        
        # Pose branch forward
        in_features = []

        body_feat = None
        for part in self.modes:
            # project position to hidden dim
            proj_feat = self.proj_linear[part](src_input[part]).permute(0,3,1,2) #B,C,T,V
            # spatial gcn forward
            gcn_feat = self.gcn_modules[part](proj_feat)
            if part == 'body':
                body_feat = gcn_feat
            else:
                assert not body_feat is None
                if part == 'left':
                    # Pose RGB fusion
                    if self.args.rgb_support:
                        gcn_feat = self.gather_feat_pose_rgb(gcn_feat, 
                                                            rgb_support_dict[f'{part}_hands'], 
                                                            rgb_support_dict[f'{part}_sampled_indices'], 
                                                            src_input[f'{part}_rgb_len'],
                                                            src_input[f'{part}_skeletons_norm'],
                                                            )
                        
                    gcn_feat = gcn_feat + body_feat[..., -2][...,None].detach()
                    
                elif part == 'right':
                    # Pose RGB fusion
                    if self.args.rgb_support:
                        gcn_feat = self.gather_feat_pose_rgb(gcn_feat, 
                                                                rgb_support_dict[f'{part}_hands'], 
                                                                rgb_support_dict[f'{part}_sampled_indices'],
                                                                src_input[f'{part}_rgb_len'],
                                                                src_input[f'{part}_skeletons_norm'],
                                                                )
                        
                    gcn_feat = gcn_feat + body_feat[..., -1][...,None].detach()

                elif part == 'face_all':
                    gcn_feat = gcn_feat + body_feat[..., 0][...,None].detach()

                else:
                    raise NotImplementedError
            
            # temporal gcn forward
            gcn_feat = self.fusion_gcn_modules[part](gcn_feat) #B,C,T,V
            pool_feat = gcn_feat.mean(-1).transpose(1,2) #B,T,C
            in_features.append(pool_feat)
        
        # concat sub-pose feature across token dimension
        vis_embeds = torch.cat(in_features, dim=-1) + self.part_para
        vis_embeds = self.pose_proj(vis_embeds) #TODO: save the inputs_embeds

        prefix_token = self.mt5_tokenizer(
                                [f"Translate sign language video to {self.lang}: "] * len(tgt_input["gt_sentence"]),
                                padding="longest",
                                truncation=True,
                                return_tensors="pt",
                            ).to(vis_embeds.device)
        
        prefix_embeds = self.hcl.early_fusion_encoder.vis_encrd.embed_tokens(prefix_token['input_ids'])
        vis_embeds = torch.cat([prefix_embeds, vis_embeds], dim=1)

        vis_attention_mask = torch.cat([prefix_token['attention_mask'],
                                    src_input['attention_mask']], dim=1)

        tgt_input_feature = self.mt5_tokenizer(tgt_input['gt_sentence'],  
                                                 return_tensors="pt",
                                                 padding=True,
                                                 truncation=True,
                                                 max_length=50)
        if self.args.use_cluster:
            embed_cluster_offset, attn_mask = self.embedding_cluster_helper.process(tgt_input_feature, return_mask=True)
            embed_cluster_offset = torch.LongTensor(embed_cluster_offset)
            embed_cluster_attn_mask = torch.LongTensor(attn_mask)
            tgt_input_feature['embed_cluster_offset'] = embed_cluster_offset
            tgt_input_feature['embed_cluster_attn_mask'] = embed_cluster_attn_mask

        labels = tgt_input_feature['input_ids']
        tgt_input_ids = labels

        cl_out = self.hcl(vis_embeds, vis_attention_mask, tgt_input_ids, tgt_input_feature)

        loss_stm = self.stm(tgt_input_ids, cl_out['txt_inputs_embeds'], cl_out['txt_hidden_states'], 
                            cl_out['vis_hidden_states'], cl_out['vis_atten_mask'], tgt_input_feature)

        labels[labels == self.mt5_tokenizer.pad_token_id] = -100
        decoder_input_ids = self.sgt_dec._shift_right(labels)
        if self.args.enc_hidden_state == 'txt':
            decoder_out = self.sgt_dec(input_ids = decoder_input_ids.to(self.args.device),
                                encoder_hidden_states=cl_out['txt_hidden_states'].to(),
                                return_dict = True,
                                )
        elif self.args.enc_hidden_state == 'vis':
            decoder_out = self.sgt_dec(input_ids = decoder_input_ids.to(self.args.device),
                                encoder_hidden_states=cl_out['vis_hidden_states'].to(),
                                return_dict = True,
                                )
        sequence_out = decoder_out[0]
        out_logits = self.sgt_dec_lm_head(sequence_out)

        label = labels.reshape(-1).to(torch.long)
        logits = out_logits.reshape(-1,out_logits.shape[-1]).to(torch.float32).to(out_logits.device)
        loss_fct = torch.nn.CrossEntropyLoss(label_smoothing=self.args.label_smoothing, ignore_index=-100).to(logits.device)
        loss_lm = loss_fct(logits, label.to(out_logits.device, non_blocking=True))

        stack_out = {
            'loss_local_stc': cl_out['loss_local_stc'],
            'loss_global_stc': cl_out['loss_global_stc'],
            'loss_stm': loss_stm,
            'loss_lm': loss_lm
        }
        return stack_out

def get_requires_grad_dict(model):
    param_requires_grad = {name: True for name, param in model.named_parameters()}
    param_requires_grad_right = {}
    for key in param_requires_grad.keys():
        if 'left' in key:
            param_requires_grad_right[key.replace("left", 'right')] = param_requires_grad[key]
    param_requires_grad = {**param_requires_grad,
                           **param_requires_grad_right}
    params_to_update = {k: v for k, v in model.state_dict().items() if param_requires_grad.get(k, True)}

    return params_to_update

class SignEFCL(nn.Module):
    """
    Ealier fusion + Contrastive learning 
    """

    def __init__(self, args):
        super(SignEFCL, self).__init__()
        self.early_fusion_encoder = EFEncoder(args)
        self.txt_encoder = self.early_fusion_encoder.txt_encrd
        self.logit_scale = nn.Parameter(torch.ones([]) * np.log(1 / 0.07))
        self.args = args
        print("row_strategy for hcl_loss:", args.row_strategy)
        print("score_strategy for hcl_loss:", args.score_strategy)

    def forward(self, vis_embeds, vis_attn_mask, tgt_input_ids, tgt_input_feature):
        early_fusion_out = self.early_fusion_encoder(vis_embeds, vis_attn_mask, tgt_input_ids, tgt_input_feature)

        loss_local_stc = 0
        if not self.args.ignore_local_cl_loss:
            vis_features = early_fusion_out['vis_hidden_states']
            text_features = early_fusion_out['txt_hidden_states']

            # normalized features
            vis_features = vis_features / vis_features.norm(dim=-1, keepdim=True).clamp(min=1e-6)
            text_features = text_features / text_features.norm(dim=-1, keepdim=True).clamp(min=1e-6)
            self.vis_features = vis_features
            
            ###============== Local-level Contrastive Learning on visual feats and text clusters ===================###
            if self.args.use_cluster:
                text_feature_cluster = do_cluster_aggreation(text_features, tgt_input_feature)
                text_features = text_feature_cluster * tgt_input_feature['embed_cluster_attn_mask'].unsqueeze(2).to(text_features.device)
            loss_local_stc = tokenwise_similarity_loss(vis_features, text_features, self.args)

        loss_global_stc = 0
        if not self.args.ignore_global_cl_loss:
            ###============== Global-level Contrastive Learning on cls tokens ===================###
            loss_global_stc = gloabal_similarity_loss(early_fusion_out['vis_global_token'], early_fusion_out['txt_global_token'], self.logit_scale, self.args)

        stack_out = {
            'loss_local_stc': loss_local_stc,
            'loss_global_stc': loss_global_stc,
            'vis_hidden_states': early_fusion_out['vis_hidden_states'],
            'vis_atten_mask':  early_fusion_out['vis_atten_mask'],
            'txt_hidden_states': early_fusion_out['txt_hidden_states'],
            'txt_inputs_embeds': early_fusion_out['txt_inputs_embeds']
        }
        return stack_out
        
class EFEncoder(nn.Module):
    def __init__(self, args, dim=768):
        super(EFEncoder, self).__init__()
        self.args = args
        # visual encoder
        self.vis_encrd = MT5ForConditionalGeneration.from_pretrained(mt5_path).get_encoder() # trans_encoder
        self.vis_cls_token = nn.Parameter(torch.randn(1, 1, dim))

        # text encoder
        self.txt_encrd = MT5ForConditionalGeneration.from_pretrained(mt5_aux_path).get_encoder()
        self.txt_cls_token = nn.Parameter(torch.randn(1, 1, dim))

        if args.freeze_txt_enc:
            for param in self.txt_encrd.parameters():
                param.requires_grad = False
            print("Early_fusion_encoder.txt_encrd is frozen.")
        
        self.fusion_layer = args.fusion_layer
        self.x_cross_attn = X_CrossAttn(args)
        print(f"Ealier fusion with cross_attn at layer {args.which_cross_attn} of mt5 decoder")

        self.vis_end_idx, self.txt_end_idx = self.compute_where_stop()
        self.vis_resume_range, self.txt_resume_range = self.compute_fusion_range()
        print(f"Vis encrd pause at {self.vis_end_idx}, fuse {str(len(self.vis_resume_range))} layers within {self.vis_resume_range} exclusive last value")
        print(f"Txt encrd pause at {self.txt_end_idx}, fuse {str(len(self.txt_resume_range))} layers within {self.txt_resume_range} exclusive last value")

    def compute_where_stop(self):
        vis_num_layers = len(self.vis_encrd.block)
        vis_end_idx = vis_num_layers - self.fusion_layer - 1

        txt_num_layers = len(self.txt_encrd.block)
        txt_end_idx = txt_num_layers - self.fusion_layer - 1
        return vis_end_idx, txt_end_idx

    def compute_fusion_range(self):
        vis_num_layers = len(self.vis_encrd.block)
        vis_range = range(self.vis_end_idx+1, vis_num_layers)

        txt_num_layers = len(self.txt_encrd.block)
        txt_range = range(self.txt_end_idx+1, txt_num_layers)
        return vis_range, txt_range
    
    def select_model(self, which_model):
        if which_model == 'vis':
            return self.vis_encrd
        elif which_model == 'txt':
            return self.txt_encrd

    def share_forward(self, which_model, input_ids = None, inputs_embeds = None, attention_mask = None, end_idx=-1, tgt_input_feature=None, this_cls_token=None):
        
        which_model_type = which_model
        which_model = self.select_model(which_model)

        if inputs_embeds is not None:
            input_shape = inputs_embeds.size()[:-1]
        elif input_ids is not None:
            input_shape = input_ids.size()
            input_ids = input_ids.view(-1, input_shape[-1])
        else:
            raise ValueError

        if inputs_embeds is None:
            inputs_embeds = which_model.embed_tokens(input_ids.to(self.args.device))

        if which_model_type == 'txt':
            if  input_ids is None or this_cls_token is None:
                raise ValueError
            inputs_embeds = torch.cat((this_cls_token.to(self.args.device), inputs_embeds), dim=1)
            input_shape = inputs_embeds.size()[:-1]

        batch_size, seq_length = input_shape
        use_cache, past_key_values_length = False, 0
        cache_position = torch.arange(
            past_key_values_length, past_key_values_length + seq_length, device=inputs_embeds.device
        )

        hidden_states = which_model.dropout(inputs_embeds)

        if attention_mask is None and not torch.compiler.is_compiling():
            # required mask seq length can be calculated via length of past cache
            mask_seq_length = past_key_values_length + seq_length
            attention_mask = torch.ones(batch_size, mask_seq_length, device=inputs_embeds.device)

        if attention_mask is not None:
            causal_mask = attention_mask[:, None, None, :]
            causal_mask = causal_mask.to(dtype=inputs_embeds.dtype)
            causal_mask = (1.0 - causal_mask) * torch.finfo(inputs_embeds.dtype).min
        else:
            causal_mask = None

        # Prepare head mask if needed
        head_mask = which_model.get_head_mask(None, which_model.config.num_layers)
        cross_attn_head_mask = which_model.get_head_mask(None, which_model.config.num_layers)

        position_bias = None
        for i, layer_module in enumerate(which_model.block[:end_idx+1]):
            layer_head_mask = head_mask[i]
            cross_attn_layer_head_mask = cross_attn_head_mask[i]

            if which_model.gradient_checkpointing and which_model.training:
                layer_outputs = which_model._gradient_checkpointing_func(
                    layer_module.forward,
                    attention_mask=causal_mask,
                    layer_head_mask=layer_head_mask,
                    cross_attn_layer_head_mask=cross_attn_layer_head_mask,
                    position_bias=position_bias,
                    # cache_position=cache_position
                )
            else:
                layer_outputs = layer_module(
                    hidden_states,
                    attention_mask=causal_mask.to(hidden_states.device),
                    layer_head_mask=layer_head_mask,
                    cross_attn_layer_head_mask=cross_attn_layer_head_mask,
                    position_bias=position_bias,
                    # cache_position=cache_position
                )
            
            layer_outputs = layer_outputs[:1] + (None,) + layer_outputs[1:]
            hidden_states, _ = layer_outputs[:2]
            position_bias = layer_outputs[2]
        return hidden_states, causal_mask, (head_mask, cross_attn_head_mask), (cache_position, position_bias), inputs_embeds
    
    def share_iteration(self, which_model, hidden_states, attention_mask, idx, head_masks, position_bias, cache_posit):
        which_model = self.select_model(which_model)

        layer_module = which_model.block[idx]

        head_mask, cross_attn_head_mask = head_masks
        layer_head_mask = head_mask[idx]
        cross_attn_layer_head_mask = cross_attn_head_mask[idx]

        if which_model.gradient_checkpointing and which_model.training:
            layer_outputs = which_model._gradient_checkpointing_func(
                layer_module.forward,
                attention_mask=attention_mask,
                layer_head_mask=layer_head_mask,
                cross_attn_layer_head_mask=cross_attn_layer_head_mask,
                position_bias=position_bias
            )
        else:
            layer_outputs = layer_module(
                hidden_states,
                attention_mask=attention_mask,
                layer_head_mask=layer_head_mask,
                cross_attn_layer_head_mask=cross_attn_layer_head_mask,
                position_bias=position_bias
            )
        
        layer_outputs = layer_outputs[:1] + (None,) + layer_outputs[1:]
        hidden_states, _ = layer_outputs[:2]
        position_bias = layer_outputs[2]
        return hidden_states, position_bias
    
    def share_norm(self, which_model, hidden_states):
        which_model = self.select_model(which_model)

        hidden_states = which_model.final_layer_norm(hidden_states)
        hidden_states = which_model.dropout(hidden_states)
        return hidden_states

    def forward(self, vis_embeds, vis_attn_mask, tgt_input_ids, tgt_input_feature):
        # Insert cls token at the beginning
        batch_size = vis_embeds.shape[0]
        vis_cls_token = repeat(self.vis_cls_token, '() n d -> b n d', b=batch_size).to(vis_embeds.device)
        vis_embeds_in = torch.cat((vis_cls_token, vis_embeds), dim=1)
        vis_attention_mask = F.pad(vis_attn_mask.flatten(1), (1, 0), value=1.)  # [b, 64] --> [b, 65]
        txt_cls_token = repeat(self.txt_cls_token, '() n d -> b n d', b=batch_size).to(tgt_input_ids.device)

        # visual encoder
        vis_hidden_states, vis_attention_mask, vis_head_masks, (vis_cache_posit, vis_posit_bias), _ = self.share_forward(
            which_model='vis', inputs_embeds=vis_embeds_in, attention_mask=vis_attention_mask.to(vis_embeds_in.device), 
            end_idx=self.vis_end_idx)
        
        # text encoder        
        txt_hidden_states, txt_attention_mask, txt_head_masks, (txt_cache_posit, txt_posit_bias), txt_inputs_embeds = self.share_forward(
            which_model='txt', input_ids=tgt_input_ids, end_idx=self.txt_end_idx, tgt_input_feature=tgt_input_feature, 
            this_cls_token=txt_cls_token)
        
        # cross-modality communication
        for vis_idx, txt_idx in zip(self.vis_resume_range, self.txt_resume_range):
            vis_hidden_states, txt_hidden_states = self.x_cross_attn(vis_hidden_states, txt_hidden_states)

            vis_hidden_states, vis_posit_bias = self.share_iteration(which_model='vis', 
                                                     hidden_states=vis_hidden_states, 
                                                     attention_mask=vis_attention_mask, 
                                                     head_masks=vis_head_masks,
                                                     position_bias=vis_posit_bias,
                                                     cache_posit = vis_cache_posit,
                                                     idx=vis_idx)
            
            txt_hidden_states, txt_posit_bias = self.share_iteration(which_model='txt', 
                                                     hidden_states=txt_hidden_states, 
                                                     attention_mask=txt_attention_mask,
                                                     head_masks=txt_head_masks, 
                                                     position_bias=txt_posit_bias,
                                                     cache_posit=txt_cache_posit,
                                                     idx=txt_idx)

        # last norm 
        vis_last_hidden_state = self.share_norm(which_model='vis', hidden_states=vis_hidden_states)
        vis_global_token = vis_last_hidden_state[:, 0, :]

        txt_last_hidden_state = self.share_norm(which_model='txt', hidden_states=txt_hidden_states)
        txt_global_token = txt_last_hidden_state[:, 0, :]

        stack_out = {
            'vis_global_token': vis_global_token,
            'txt_global_token': txt_global_token,
            'vis_hidden_states': vis_last_hidden_state,
            'txt_hidden_states': txt_last_hidden_state,
            'vis_atten_mask': vis_attention_mask,
            'txt_atten_mask': txt_attention_mask,
            'txt_inputs_embeds': txt_inputs_embeds
        }
        return stack_out


class TxtEncoder(nn.Module):

    def __init__(self) -> None:
        super(TxtEncoder, self).__init__()
        self.txt_encrd = MT5ForConditionalGeneration.from_pretrained(mt5_aux_path).get_encoder()

    def forward(self, input_ids = None, attention_mask = None, tgt_input_feature=None, this_cls_token=None):

        if input_ids is None or tgt_input_feature is None:
            raise ValueError
        
        input_shape = input_ids.size()
        input_ids = input_ids.view(-1, input_shape[-1])
        inputs_embeds = self.txt_encrd.embed_tokens(input_ids.to(self.args.device))

        if tgt_input_feature is None or input_ids is None or this_cls_token is None:
            raise ValueError
        inputs_embeds = torch.cat((this_cls_token, inputs_embeds), dim=1)
        attention_mask = tgt_input_feature["embed_cluster_attn_mask"]
        attention_mask = F.pad(attention_mask.flatten(1), (1, 0), value=1.)  # [b, n] --> [b, n+1]

        hidden_states = self.txt_encrd.dropout(inputs_embeds)

        # if attention_mask is not None:
        causal_mask = attention_mask[:, None, None, :]
        causal_mask = causal_mask.to(dtype=inputs_embeds.dtype)
        causal_mask = (1.0 - causal_mask) * torch.finfo(inputs_embeds.dtype).min

        # Prepare head mask if needed
        head_mask = self.txt_encrd.get_head_mask(None, self.txt_encrd.config.num_layers)
        cross_attn_head_mask = self.txt_encrd.get_head_mask(None, self.txt_encrd.config.num_layers)

        position_bias = None
        for i, layer_module in enumerate(self.txt_encrd.block):
            layer_head_mask = head_mask[i]
            cross_attn_layer_head_mask = cross_attn_head_mask[i]

            if self.txt_encrd.gradient_checkpointing and self.txt_encrd.training:
                layer_outputs = self.txt_encrd._gradient_checkpointing_func(
                    layer_module.forward,
                    attention_mask=causal_mask,
                    layer_head_mask=layer_head_mask,
                    cross_attn_layer_head_mask=cross_attn_layer_head_mask,
                    position_bias=position_bias
                )
            else:
                layer_outputs = layer_module(
                    hidden_states,
                    attention_mask=causal_mask,
                    layer_head_mask=layer_head_mask,
                    cross_attn_layer_head_mask=cross_attn_layer_head_mask,
                    position_bias=position_bias
                )
            
            layer_outputs = layer_outputs[:1] + (None,) + layer_outputs[1:]
            hidden_states, _ = layer_outputs[:2]
            position_bias = layer_outputs[2]

        hidden_states = self.txt_encrd.final_layer_norm(hidden_states)
        hidden_states = self.dropout(hidden_states)
        return hidden_states, inputs_embeds

class STM(nn.Module):

    def __init__(self, args, dim=768) -> None:
        super(STM, self).__init__()
        self.args = args
        self.sgt_encoder = SGTEncoder(args)
        self.temp = nn.Parameter(0.07*torch.ones([]))   
        self.stm_head = nn.Linear(dim, 2) 

    def forward(self, txt_input_ids, txt_embeds, txt_enc_hidden_state, vis_enc_hidden_state, vis_atten_mask, tgt_input_feature):
        ###============== sign-text Matching ===================###
        # positive visual-text pairs
        output_pos_stack = self.sgt_encoder(txt_hidden_state = txt_enc_hidden_state, 
                                  txt_input_ids = txt_input_ids,
                                  tgt_input_feature = tgt_input_feature,
                                  vis_hidden_state = vis_enc_hidden_state, 
                                  vis_atten_mask = vis_atten_mask)
        output_pos = output_pos_stack['output_pos']

        # negative visual-text pairs
        sign_attention_mask = vis_atten_mask.cuda()
        # sign_embeds = vis_enc_hidden_state[:, None, :].expand(vis_enc_hidden_state.shape[0], 1, vis_enc_hidden_state.shape[1])
        sign_embeds = vis_enc_hidden_state
        txt_input_ids = txt_input_ids.cuda()     
        bs = txt_input_ids.shape[0]

        with torch.no_grad():      
            mask = torch.eye(txt_input_ids.shape[0], device=txt_input_ids.device, dtype=bool,
                             requires_grad=False)

            image_feat_world = self.concat_all_gather(sign_embeds[:,0,:])
            text_feat_world = self.concat_all_gather(txt_embeds[:,0,:])

            sim_i2t = sign_embeds[:,0,:] @ text_feat_world.t() / self.temp 
            sim_t2i = txt_embeds[:,0,:] @ image_feat_world.t() / self.temp 

            weights_i2t = F.softmax(sim_i2t,dim=1)
            weights_t2i = F.softmax(sim_t2i,dim=1)

            weights_i2t = torch.nan_to_num(weights_i2t, nan=0.0, posinf=1.0, neginf=0.0)
            weights_t2i = torch.nan_to_num(weights_t2i, nan=0.0, posinf=1.0, neginf=0.0)

            weights_i2t = torch.clamp(weights_i2t.to(mask.device), min=1e-6)
            weights_t2i = torch.clamp(weights_t2i.to(mask.device), min=1e-6)

            weights_i2t.masked_fill_(mask, 0)       
            weights_t2i.masked_fill_(mask, 0)         

        # select a negative visual for each text
        sign_embeds_neg = []    
        for b in range(bs):
            if weights_t2i[b].sum() == 0:
                weights_t2i[b] = torch.ones_like(weights_t2i[b]) 
                weights_t2i[b] /= weights_t2i[b].sum() 
            neg_idx = torch.multinomial(weights_t2i[b], 1).item()
            sign_embeds_neg.append(sign_embeds[neg_idx])
        sign_embeds_neg = torch.stack(sign_embeds_neg,dim=0)   

        # select a negative text (from same ranks) for each visual
        text_ids_neg = []
        text_atts_neg = []
        for b in range(bs):
            if weights_i2t[b].sum() == 0:
                weights_i2t[b] = torch.ones_like(weights_i2t[b])  
                weights_i2t[b] /= weights_i2t[b].sum()
            neg_idx = torch.multinomial(weights_i2t[b], 1).item()
            text_ids_neg.append(txt_input_ids[neg_idx].cuda())
        text_ids_neg = torch.stack(text_ids_neg,dim=0)   
        text_ids_all = torch.cat([txt_input_ids.cuda(), text_ids_neg],dim=0)     
        
        sign_embeds_all = torch.cat([sign_embeds_neg, sign_embeds],dim=0)
        sign_atts_all = torch.cat([sign_attention_mask, sign_attention_mask],dim=0)

        output_neg_stack = self.sgt_encoder(txt_input_ids = text_ids_all, 
                                      vis_hidden_state = sign_embeds_all,
                                      vis_atten_mask = sign_atts_all, 
                                      neg=True)    
        output_neg = output_neg_stack['output_neg']

        vl_embeddings = torch.cat([output_pos[:,0,:], output_neg[:,0,:]],dim=0)

        vl_output = self.stm_head(vl_embeddings).to(torch.float32)      
        itm_labels = torch.cat([torch.ones(bs,dtype=torch.long),torch.zeros(2*bs,dtype=torch.long)],
                               dim=0).to(torch.long).to(vl_output.device)
        loss_itm = F.cross_entropy(vl_output, itm_labels)  
        return loss_itm
    
    @torch.no_grad()
    def concat_all_gather(self, tensor):
        """
        Performs all_gather operation on the provided tensors.
        *** Warning ***: torch.distributed.all_gather has no gradient.
        """
        if torch.distributed.is_initialized():
            tensors_gather = [torch.ones_like(tensor) for _ in range(torch.distributed.get_world_size())]
            torch.distributed.all_gather(tensors_gather, tensor, async_op=False)
            output = torch.cat(tensors_gather, dim=0)
        else:
            output = tensor
        return output


class SGTEncoder(nn.Module):
    def __init__(self, args, dim=768) -> None:
        super(SGTEncoder, self).__init__()
        # Use the self_attn and cross from middle to last; Use the cross_attn from start to end
        self.args = args
        self.mt5_aux_enc = MT5ForConditionalGeneration.from_pretrained(mt5_aux_path).get_encoder()
        self.block = self.mt5_aux_enc.block[args.strat_self_attn_ly:]
        self.txt_enc_token = nn.Parameter(torch.randn(1, 1, dim))

        mt5_dec = MT5ForConditionalGeneration.from_pretrained(mt5_path).get_decoder()
        self.cross_attns = nn.ModuleList([blockk.layer[1] for blockk in mt5_dec.block[1:args.end_cross_attn_enc_ly]]) # cross_attn is placed at the 2nd of the layer, given that it's decdr        
        print(f"Late fusion with cross_attn of mt5 txt_decdr layer(s) [1:{args.end_cross_attn_enc_ly}]" + 
              f"\n self_attn of mt5_aux txt_encdr layer(s) [{args.strat_self_attn_ly}:]") 

    def refine_cross_attns(self):
        if len(self.block) != len(self.cross_attns): raise ValueError
        self.add_cross_attns()
        print(f"SGE of {len(self.block)} layers")

    def add_cross_attns(self):
        for i, cross_attn in enumerate(self.cross_attns):
            self_attn = self.block[i].layer[0]
            ff = self.block[i].layer[1]
            self.block[i].layer = nn.ModuleList([self_attn, cross_attn, ff])
        self.cross_attns = None

    def forward(self, vis_hidden_state=None, vis_atten_mask=None, txt_hidden_state=None, txt_input_ids=None, tgt_input_feature=None, neg=False):
        txt_input_embeds = self.mt5_aux_enc.embed_tokens(txt_input_ids.to(self.args.device))
        txt_hidden_state = txt_input_embeds
    
        txt_input_shape = txt_hidden_state.shape[:2]
        hidden_states = self.mt5_aux_enc.dropout(txt_hidden_state)

        batch_size, seq_length = txt_input_shape
        past_key_values_length = 0
        cache_position = None
        if cache_position is None:
            cache_position = torch.arange(
                past_key_values_length, past_key_values_length + seq_length, device=hidden_states.device
            )

        head_mask, cross_attn_head_mask = None, None
        head_mask = self.mt5_aux_enc.get_head_mask(head_mask, self.mt5_aux_enc.config.num_layers)
        cross_attn_head_mask = self.mt5_aux_enc.get_head_mask(cross_attn_head_mask, self.mt5_aux_enc.config.num_layers)
        position_bias = None
        for i, layer_module in enumerate(self.block):
            layer_head_mask = head_mask[i]
            cross_attn_layer_head_mask = cross_attn_head_mask[i]

            if self.mt5_aux_enc.gradient_checkpointing and self.training:
                layer_outputs = self.mt5_aux_enc._gradient_checkpointing_func(
                    layer_module.forward,
                    hidden_states,
                    attention_mask=None,
                    position_bias=position_bias,
                    encoder_hidden_states=vis_hidden_state,
                    encoder_attention_mask=vis_atten_mask,
                    layer_head_mask=layer_head_mask,
                    cross_attn_layer_head_mask=cross_attn_layer_head_mask,
                    # cache_position=cache_position
                )
            else:
                layer_outputs = layer_module(
                    hidden_states,
                    attention_mask=None,
                    position_bias=position_bias,
                    encoder_hidden_states=vis_hidden_state,
                    encoder_attention_mask=vis_atten_mask,
                    layer_head_mask=layer_head_mask,
                    cross_attn_layer_head_mask=cross_attn_layer_head_mask,
                    # cache_position=cache_position
                )

            layer_outputs = layer_outputs[:1] + (None,) + layer_outputs[1:]
            hidden_states, _ = layer_outputs[:2]
            position_bias = layer_outputs[2]

        hidden_states = self.mt5_aux_enc.final_layer_norm(hidden_states)
        hidden_states = self.mt5_aux_enc.dropout(hidden_states)
        output = hidden_states
        stack_out = {
            'output_pos': hidden_states if neg is False else None,
            'output_neg': hidden_states if neg is True else None,
            'txt_input_embeds': txt_input_embeds
        }
        return stack_out

def do_cluster_aggreation(hidden_state, tgt_input_feature):
    batch_size, seq_len, text_width = hidden_state.shape
    embedding_input = torch.arange(batch_size * seq_len, device=hidden_state.device)

    text_embed_cluster = F.embedding_bag(
        embedding_input,
        hidden_state.view(-1, text_width),
        tgt_input_feature["embed_cluster_offset"].to(hidden_state.device),
        mode='sum'  
    ).view(batch_size, -1, text_width)

    return text_embed_cluster
